id = "xy-zed"
name = "XY-Zed Theme"
version = "0.1.3"
schema_version = 1
authors = ["Daniel Zarifpour <z@rifpour.xyz>"]
description = "ğŸˆâ€â¬› A sleek and sophisticated dark theme with vibrant, intelligent syntax highlighting. Please report issues â©"
repository = "https://github.com/zarifpour/xy-zed"
